import { generateASTMapFromMinimizedFunctions } from '@/shared/utils/generate-ast-map';
import { generateLayoutForAllOutputs } from '@/shared/utils/logic-gate-layout-generator';
import { MinimizedFunction } from '../../LogicMinimizer.model';
import { updatedEdgesMap, updatedNodesMap } from './AutoGeneratedGateLayout.utils';

self.onmessage = function (event) {
  try {
    const minimizedFunctions: MinimizedFunction[] | null = event.data?.minimizedFunctions ?? null;

    if (!minimizedFunctions) {
      self.postMessage(null);
      return;
    }

    const astMap = generateASTMapFromMinimizedFunctions(minimizedFunctions);
    const layout = generateLayoutForAllOutputs(astMap);
    const updatedNodes = updatedNodesMap(layout);
    const updatedEdges = updatedEdgesMap(layout);

    self.postMessage({ updatedNodes, updatedEdges });
  } catch (error) {
    console.error('Worker error:', error);
    self.postMessage(null);
  }
};
